// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fashion-bold/Detalhe.tsx": () => import("../components/mockups/fashion-bold/Detalhe.tsx"),
  "./components/mockups/fashion-bold/Resultados.tsx": () => import("../components/mockups/fashion-bold/Resultados.tsx"),
  "./components/mockups/fashion-bold/Upload.tsx": () => import("../components/mockups/fashion-bold/Upload.tsx"),
  "./components/mockups/fashion-chic/Detalhe.tsx": () => import("../components/mockups/fashion-chic/Detalhe.tsx"),
  "./components/mockups/fashion-chic/Resultados.tsx": () => import("../components/mockups/fashion-chic/Resultados.tsx"),
  "./components/mockups/fashion-chic/Upload.tsx": () => import("../components/mockups/fashion-chic/Upload.tsx"),
  "./components/mockups/fashion-editora/Detalhe.tsx": () => import("../components/mockups/fashion-editora/Detalhe.tsx"),
  "./components/mockups/fashion-editora/Resultados.tsx": () => import("../components/mockups/fashion-editora/Resultados.tsx"),
  "./components/mockups/fashion-editora/Upload.tsx": () => import("../components/mockups/fashion-editora/Upload.tsx")
};
