import { db, categoriesTable, storesTable, productsTable } from "@workspace/db";

async function seed() {
  console.log("🌱 Seeding FindFit database...");

  // Categories
  await db.delete(categoriesTable);
  await db.insert(categoriesTable).values([
    { label: "Todos", value: "todos" },
    { label: "Vestidos", value: "vestido" },
    { label: "Tops", value: "top" },
    { label: "Saias", value: "saia" },
    { label: "Conjuntos", value: "conjunto" },
    { label: "Calças", value: "calca" },
  ]);
  console.log("✅ Categories seeded");

  // Stores
  await db.delete(storesTable);
  const [zara, mango, farm, cos, lelis, renner, amaro, hm] = await db
    .insert(storesTable)
    .values([
      {
        name: "Zara",
        type: "hibrido",
        url: "https://www.zara.com/br/",
        address: "Av. Paulista, 2064, São Paulo, SP",
        latitude: -23.5632,
        longitude: -46.6545,
      },
      {
        name: "Mango",
        type: "hibrido",
        url: "https://www.mango.com/br/",
        address: "R. Oscar Freire, 977, São Paulo, SP",
        latitude: -23.5629,
        longitude: -46.6691,
      },
      {
        name: "Farm Rio",
        type: "hibrido",
        url: "https://www.farmrio.com.br/",
        address: "Rua Harmonia, 484, São Paulo, SP",
        latitude: -23.5543,
        longitude: -46.6849,
      },
      {
        name: "COS",
        type: "online",
        url: "https://www.cos.com/br/",
        address: "Av. Brigadeiro Faria Lima, 2232, São Paulo, SP",
        latitude: -23.5767,
        longitude: -46.6879,
      },
      {
        name: "Le Lis Blanc",
        type: "fisico",
        url: "https://www.lelis.com.br/",
        address: "Alameda Lorena, 1765, São Paulo, SP",
        latitude: -23.5682,
        longitude: -46.6588,
      },
      {
        name: "Renner",
        type: "hibrido",
        url: "https://www.lojasrenner.com.br/",
        address: "Av. Paulista, 900, São Paulo, SP",
        latitude: -23.5668,
        longitude: -46.6520,
      },
      {
        name: "AMARO",
        type: "online",
        url: "https://amaro.com/",
        address: "R. Fidalga, 521, São Paulo, SP",
        latitude: -23.5558,
        longitude: -46.6848,
      },
      {
        name: "H&M",
        type: "hibrido",
        url: "https://www2.hm.com/pt_br/",
        address: "Shopping Ibirapuera, São Paulo, SP",
        latitude: -23.5914,
        longitude: -46.6610,
      },
    ])
    .returning();

  console.log("✅ Stores seeded");

  // Products — all in white/ivory/champagne palette
  await db.delete(productsTable);
  await db.insert(productsTable).values([
    // Vestidos
    {
      name: "Vestido Midi Slip Acetinado",
      category: "vestido",
      color: "marfim",
      material: "Acetinado",
      composition: "100% Poliéster",
      imageUrl: "/images/products/product-01.jpg",
      price: 299.9,
      storeId: zara.id,
      storeName: "Zara",
      storeType: "hibrido",
      storeUrl: "https://www.zara.com/br/",
      storeCollection: "Studio Collection",
      shipping: "Entrega grátis acima de R$200",
      sponsored: true,
      badgeLabel: "Mais parecido",
      similarityBase: 0.98,
    },
    {
      name: "Vestido Longo Crepe Off-White",
      category: "vestido",
      color: "off-white",
      material: "Crepe",
      composition: "95% Viscose, 5% Elastano",
      imageUrl: "/images/products/product-02.jpg",
      price: 349.9,
      storeId: mango.id,
      storeName: "Mango",
      storeType: "hibrido",
      storeUrl: "https://www.mango.com/br/",
      storeCollection: "Essentials",
      shipping: "Frete grátis",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.95,
    },
    {
      name: "Vestido Bias-Cut Satin",
      category: "vestido",
      color: "champagne",
      material: "Satin",
      composition: "100% Seda",
      imageUrl: "/images/products/product-03.jpg",
      price: 1290.0,
      storeId: lelis.id,
      storeName: "Le Lis Blanc",
      storeType: "fisico",
      storeUrl: "https://www.lelis.com.br/",
      storeCollection: "Resort 2025",
      shipping: "Frete a calcular",
      sponsored: false,
      badgeLabel: "Premium",
      similarityBase: 0.93,
    },
    {
      name: "Vestido Longo Chiffon Branco",
      category: "vestido",
      color: "branco",
      material: "Chiffon",
      composition: "100% Poliéster",
      imageUrl: "/images/products/product-04.jpg",
      price: 890.0,
      storeId: cos.id,
      storeName: "COS",
      storeType: "online",
      storeUrl: "https://www.cos.com/br/",
      storeCollection: "Core",
      shipping: "Frete grátis em compras acima de R$300",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.91,
    },
    {
      name: "Vestido Acetinado Alça Fina",
      category: "vestido",
      color: "branco",
      material: "Acetinado",
      composition: "90% Poliéster, 10% Elastano",
      imageUrl: "/images/products/product-05.jpg",
      price: 189.9,
      storeId: renner.id,
      storeName: "Renner",
      storeType: "hibrido",
      storeUrl: "https://www.lojasrenner.com.br/",
      storeCollection: null,
      shipping: "Frete a calcular",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.89,
    },
    {
      name: "Vestido Midi Elegance",
      category: "vestido",
      color: "champagne",
      material: "Jacquard",
      composition: "65% Algodão, 35% Poliéster",
      imageUrl: "/images/products/product-06.jpg",
      price: 520.0,
      storeId: farm.id,
      storeName: "Farm Rio",
      storeType: "hibrido",
      storeUrl: "https://www.farmrio.com.br/",
      storeCollection: "Branco Total",
      shipping: "Frete grátis",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.88,
    },
    {
      name: "Vestido Wrap Midi Branco",
      category: "vestido",
      color: "branco",
      material: "Crepe de viscose",
      composition: "100% Viscose",
      imageUrl: "/images/products/product-07.jpg",
      price: 199.9,
      storeId: hm.id,
      storeName: "H&M",
      storeType: "hibrido",
      storeUrl: "https://www2.hm.com/pt_br/",
      storeCollection: "Conscious",
      shipping: "Frete a calcular",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.86,
    },
    {
      name: "Vestido Cocktail Slip Nude",
      category: "vestido",
      color: "nude",
      material: "Acetinado",
      composition: "100% Poliéster",
      imageUrl: "/images/products/product-08.jpg",
      price: 320.0,
      storeId: amaro.id,
      storeName: "AMARO",
      storeType: "online",
      storeUrl: "https://amaro.com/",
      storeCollection: "Evening Edit",
      shipping: "Frete grátis",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.85,
    },
    {
      name: "Vestido Midi Jacquard Off-White",
      category: "vestido",
      color: "off-white",
      material: "Jacquard",
      composition: "50% Algodão, 50% Poliéster",
      imageUrl: "/images/products/product-09.jpg",
      price: 399.0,
      storeId: amaro.id,
      storeName: "AMARO",
      storeType: "online",
      storeUrl: "https://amaro.com/",
      storeCollection: "Bridal Edit",
      shipping: "Frete grátis",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.84,
    },
    // Tops
    {
      name: "Blusa Satin Ombro a Ombro",
      category: "top",
      color: "branco",
      material: "Satin",
      composition: "95% Poliéster, 5% Elastano",
      imageUrl: "/images/products/product-10.jpg",
      price: 149.9,
      storeId: zara.id,
      storeName: "Zara",
      storeType: "hibrido",
      storeUrl: "https://www.zara.com/br/",
      storeCollection: null,
      shipping: "Entrega grátis acima de R$200",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.82,
    },
    {
      name: "Top Blusê Curto Marfim",
      category: "top",
      color: "marfim",
      material: "Viscose",
      composition: "100% Viscose",
      imageUrl: "/images/products/product-11.jpg",
      price: 139.9,
      storeId: renner.id,
      storeName: "Renner",
      storeType: "hibrido",
      storeUrl: "https://www.lojasrenner.com.br/",
      storeCollection: null,
      shipping: "Frete a calcular",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.80,
    },
    // Saias
    {
      name: "Saia Midi Satin Champagne",
      category: "saia",
      color: "champagne",
      material: "Satin",
      composition: "100% Poliéster",
      imageUrl: "/images/products/product-12.jpg",
      price: 590.0,
      storeId: lelis.id,
      storeName: "Le Lis Blanc",
      storeType: "fisico",
      storeUrl: "https://www.lelis.com.br/",
      storeCollection: "Evening",
      shipping: "Frete a calcular",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.79,
    },
    // Conjuntos
    {
      name: "Conjunto Top e Saia Midi Off-White",
      category: "conjunto",
      color: "off-white",
      material: "Crepe",
      composition: "95% Viscose, 5% Elastano",
      imageUrl: "/images/products/product-13.jpg",
      price: 680.0,
      storeId: farm.id,
      storeName: "Farm Rio",
      storeType: "hibrido",
      storeUrl: "https://www.farmrio.com.br/",
      storeCollection: "Branco Total",
      shipping: "Frete grátis",
      sponsored: false,
      badgeLabel: "Exclusivo",
      similarityBase: 0.78,
    },
    // Calças
    {
      name: "Calça Pantalona Linho Bege",
      category: "calca",
      color: "bege",
      material: "Linho",
      composition: "55% Linho, 45% Viscose",
      imageUrl: "/images/products/product-14.jpg",
      price: 279.9,
      storeId: mango.id,
      storeName: "Mango",
      storeType: "hibrido",
      storeUrl: "https://www.mango.com/br/",
      storeCollection: null,
      shipping: "Frete grátis",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.76,
    },
    {
      name: "Vestido Longo Plissado Branco",
      category: "vestido",
      color: "branco",
      material: "Plissado",
      composition: "100% Poliéster",
      imageUrl: "/images/products/product-15.jpg",
      price: 750.0,
      storeId: cos.id,
      storeName: "COS",
      storeType: "online",
      storeUrl: "https://www.cos.com/br/",
      storeCollection: "Movement",
      shipping: "Frete grátis em compras acima de R$300",
      sponsored: false,
      badgeLabel: null,
      similarityBase: 0.75,
    },
  ]);
  console.log("✅ Products seeded (15 products)");
  console.log("🎉 Seed complete!");
  process.exit(0);
}

seed().catch((e) => {
  console.error("❌ Seed failed:", e);
  process.exit(1);
});
